baseURL: http://www.murmuredesforets.fr/
languageCode: fr-fr
title: Site de demonstration
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak