baseURL: https://lassembleuse.github.io/hugo-starter/
languageCode: fr-fr
title: Site de demonstration
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak