baseURL: https://www.murmuredesforets.fr/
languageCode: fr-fr
title: Murmure des forêts
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
removePathAccents: true
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak

permalinks:
  actualites: /:year/:month/:title/